# Generated by Django 4.2.29 on 2026-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_remove_reservation_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
