# Generated by Django 4.2.30 on 2026-04-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0011_merge_20260419_1754'),
        ('bikes', '0011_merge_20260420_1258'),
    ]

    operations = [
    ]
